[versions]
agp = "8.2.2"
kotlin = "2.0.0"
hilt = "2.49"
junit5 = "1.10.0.0"
ksp = "2.0.0-1.0.22"
ktlint = "12.1.0"
jacoco = "0.8.9"
activity-compose = "1.8.2"
compose-bom = "2025.01.00"
compose-ui = "1.7.6"
material3 = "1.3.1"
navigation-compose = "2.8.5"
coil-compose = "2.4.0"
junit = "1.2.1"
espresso = "3.6.1"
hilt-navigation-compose = "1.2.0"
retrofit = "2.9.0"
logging-interceptor = "4.11.0"
converter-gson = "2.9.0"
coroutines-adapter = "0.9.2"
coroutines-test = "1.10.1"
junit-jupiter = "5.10.1"
mockito-kotlin = "5.0.0"
junit4 = "4.13.2"
ui-test-junit4 = "1.7.6"
vintage-engine = "5.10.1"
timber = "5.0.1"
room = "2.6.1"
test-rules = "1.6.1"

[libraries]
# Root BuildScript
androidGradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt"  }
junit5Plugin = { module= "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "junit5" }
ktlintGradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
jacocoCore = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }

# Android Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
material3 = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }

# Android Compose Testing
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui-test-junit4" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui-test-junit4" }

# Hilt
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

# Retrofit 2
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter-gson" }

# Coroutines
coroutines-adapter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlin-coroutines-adapter", version.ref = "coroutines-adapter" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }

# Junit 5
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }

# Junit 4
junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "vintage-engine" }

# Timber Logger
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "junit5" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jacoco = { id = "jacoco" }
